Added downgrade functionality
LSSTDESC/healsparse pull request #10
Opened 2019-03-07 05:17 UTC by fjaviersanchez

I added the downgrade functionality but I made a lot of design choices (e.g, I subbed the `hp.UNSEEN` values by `np.nan` to then calculate the mean). I also decided that this modifies the original `sparseMap`, `nsideSparse` and `bitShift` attributes. Please, let me know if you agree with these choices or you would prefer to expose the method and put a `sparseMap` as input and return a `sparseMap` rather than modifying the original.

2019-03-07 05:33 UTC, erykoff requested changes
So this is going to run into problems with the new format I just pushed.  (hopefully the travis checks catch that!)
I am thinking about the degrade-in-place rather than creating a new map.  I think that the best option is to create a new map, actually, and then if somebody wants to replace it they can do `sparseMap = sparseMap.degrade()` or if they want to hold the old one they do `newSparseMap = sparseMap.degrade()`.

2019-03-07 05:33 UTC, erykoff commented on healsparse/healSparseMap.py
> +           print('nside_out should be smaller than nside for the sparseMap')
This should actually raise an exception.  Try:
```
if self._nsideSparse > nside_out:
    raise ValueError('nside_out should be smaller than nside for the sparseMap')
```

2019-03-07 05:33 UTC, erykoff commented on healsparse/healSparseMap.py
> +        self._sparseMap = np.nanmean(self._sparseMap.reshape((npop_pix+1, (nside_out//self._nsideCoverage)**2, -1)), axis=2).flatten()
That's very clever, I didn't know about `np.nanmean` and I bet that takes care of things.  Note that this only works with the `reduction='mean'` option, we should either remove that for the time being, or flag that we will add a (e.g.) median in the future (which will be more expensive of course).

2019-03-07 05:33 UTC, erykoff commented on healsparse/healSparseMap.py
> +        self._sparseMap = np.nanmean(self._sparseMap.reshape((npop_pix+1, (nside_out//self._nsideCoverage)**2, -1)), axis=2).flatten()
So this is going to be have to be updated for the recarray support.  I think that's pretty easy.  If it's a recarray (`self._isRecArray`) then you need to (a) set the sparseMap dtype; (b) loop over fields; but (c) the `UNSEEN` check is on `self._sparseMap[self._primary] == hp.UNSEEN`.
Oh, I just realized that this won't work with the "in-place" replacement, but that's only a couple more lines.

2019-03-08 05:24 UTC, fjaviersanchez commented
Thanks! Do you suggest then to write the method into a separate file then (`ud_grade.py`?) or should I keep it in `healSparseMap.py`?

2019-03-08 05:26 UTC, erykoff commented
I mean it should be in `HealSparseMap`, it can create one of itself.  So you can call `newMap = oldMap.degrade(nside)` like that.

2019-03-08 23:06 UTC, fjaviersanchez commented
since the `hp.UNSEEN` are converted to `np.nan` and the `np.nanmean` or `np.nanmedian` of an array filled with `np.nan` are `np.nan` we could just convert back `np.nan` to `hp.UNSEEN`

2019-03-18 04:19 UTC, fjaviersanchez commented
@erykoff Sorry for the delay. Here are the requested changes. I had to separate the recarrays from the regular ndarrays since they were giving trouble with the `np.nan` stuff. I generated a specific test for them including lookups. Please, let me know if you'd like me to restructure anything or have any other requests. Also, I can add more documentation throughout the code in this PR or I can open a new PR dedicated to that. Thanks in advance!

2019-03-22 22:07 UTC, erykoff approved these changes
Sorry for the long delay, I was travelling.  I think this looks good, with the comment below that might let us add the median functionality (unless I'm missing something, which is very possible).

2019-03-22 22:07 UTC, erykoff commented on healsparse/healSparseMap.py
> +                wgt = np.ones_like(aux, dtype=np.float)
I think this should work (and it does in the tests) but I think we can use the same code as below (`nanmean` etc), we just need to make sure that `aux = self._sparseMap[key].astype(np.float)` and then filling with `NaN`s.  Then we can get the median functionality as well.

2019-03-25 16:41 UTC, erykoff approved these changes

2019-03-25 16:45 UTC, merged