Add support for pixel ranges and composable geometries.
LSSTDESC/healsparse pull request #151
Opened 2024-01-20 23:16 UTC by erykoff

This completely refactors the packed boolean arrays to be more efficient, and to work with arbitrary slices.  This enables setting of giant pixel ranges (large area masks) with minimal memory overhead.

2024-01-23 20:14 UTC, beckermr requested changes
I left a few comments. Congrats on the test suite. It was painful to read and no doubt it was painful to write!

2024-01-23 20:14 UTC, beckermr commented on tests/test_pixel_ranges.py
> +        healsparse.healSparseMap.PIXEL_RANGE_THRESHOLD = 0
Don't you need to setup and teardown this patching?

2024-01-23 20:14 UTC, beckermr commented on tests/test_pixel_ranges.py
> +        healsparse.healSparseMap.PIXEL_RANGE_THRESHOLD = 0
Same for the ones below.

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +            if start_index < 0 or start_index > 7:
I don't understand why this is a constraint. Sure the user could waste memory, but do we care if they do something less optimal?

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +        return self._stop_index - self._start_index
Don't you need a `+1` here since if you have, eg., start_index = 0 and stop_index = 9, there are 10 elements?

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +        return self._stop_index - self._start_index
`stop_index` is defined as the "index at which the array ends" in the doc string. However, given how it is computed and used, I think it is actual one plus the last index.

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +            raise NotImplementedError("Cannot yet get data array from offset array")
This error message confuses me a lot.

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +            new_buffer[-1] = np.packbits(last_unpacked[0], bitorder="little")
Why is this block needed? Since start and stop don't change, isn't the existing data already packaged correctly? Maybe add a comment?

2024-01-23 20:14 UTC, beckermr commented on healsparse/packedBoolArray.py
> +        raise RuntimeError("Programmer mistake")
This needs a better error message.

2024-01-23 20:14 UTC, beckermr commented on tests/test_packedboolarray.py
> +        middle_arrays.append(_PackedBoolArray(data_buffer=data.copy(), start_index=0, stop_index=16))
The last index is 15 in this case. Another example of how the doc string and parameter names do not match how they are used.

2024-01-23 20:14 UTC, beckermr commented on tests/test_packedboolarray.py
> +            pba = _PackedBoolArray(size=20, start_index=-1)
-1? That is allowed?

2024-01-23 20:16 UTC, beckermr commented on tests/test_packedboolarray.py
> +            pba = _PackedBoolArray(size=20, start_index=-1)
woops missed the assertRaises in the confusing diff! sorry!

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +            if start_index < 0 or start_index > 7:
The unaligned ends of the array need special handling because they need to be unpacked to be able to use them.  And if I allow another trailing bit of data that shouldn't be touched when doing an operation then I think I have to make that already annoying logic even more complex.

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +        return self._stop_index - self._start_index
Ah yes, it is the exclusive stop index, like a python slice.  I will correct the docstring.

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +            if start_index < 0 or start_index > 7:
Though now that I think about it some more, I can always just create a view on construction.  But after spending 15 minutes on this, I have broken everything terribly and don't have time to redo all the index math for the fully general case.

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +            raise NotImplementedError("Cannot yet get data array from offset array")
How about `_PackedBoolArray does not support extracting the data_array from an unaligned _PackedBoolArray.`. This is one of those "it kind of works but will give surprising results in some cases".

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +            new_buffer[-1] = np.packbits(last_unpacked[0], bitorder="little")
I want to mask any extraneous bits which may have any value depending on how things were originally sliced.

2024-01-24 18:45 UTC, erykoff commented on healsparse/packedBoolArray.py
> +        raise RuntimeError("Programmer mistake")
Should just be removed.

2024-01-24 18:45 UTC, erykoff commented on tests/test_packedboolarray.py
> +        middle_arrays.append(_PackedBoolArray(data_buffer=data.copy(), start_index=0, stop_index=16))
Fixed the docstring.

2024-01-24 21:27 UTC, beckermr commented on healsparse/packedBoolArray.py
> +            if start_index < 0 or start_index > 7:
understood!

2024-01-24 21:27 UTC, beckermr approved these changes

2024-01-25 00:44 UTC, merged