Added plotting routines
LSSTDESC/healsparse pull request #24
Opened 2019-06-17 22:32 UTC by fjaviersanchez

I added the method `hsp_view_map` in `visu_func` to visualize `HealSparseMap` objects. I added some (optional) dependencies in order to support multiple projections. 

I'm still missing an update on the tutorial notebook but, please feel free to take a look at the code and make any suggestions/comments/requests.

Thanks!

2019-06-17 22:41 UTC, fjaviersanchez commented
Actually `cartopy` is not optional with the current implementation but I can try to make it optional if necessary.

2019-06-18 05:41 UTC, fjaviersanchez commented
I made it optional so the Travis-CI tests would be skipped. I'm planning to add another environment where the tests are performed.

2019-06-18 10:47 UTC, esheldon commented
I get this error:

```
File "/home/esheldon/miniconda3/envs/default/lib/python3.7/site-packages/healsparse-0.0.7-py3.7.egg/healsparse/visu_func.py", line 169, in hsp_view_map

AttributeError: 'AxesSubplot' object has no attribute 'set_global'
```

2019-06-18 10:49 UTC, esheldon commented
that is because cartopy is not instlalled, so it looks like you probably need to raise an exception if cartopy isn't available, at least with the current code

2019-06-18 10:59 UTC, esheldon requested changes

2019-06-18 10:59 UTC, esheldon commented on healsparse/visu_func.py
>      from cartopy.mpl.gridliner import LATITUDE_FORMATTER, LONGITUDE_FORMATTER
you need to set `have_cartopy = True`

2019-06-18 10:59 UTC, esheldon commented on healsparse/visu_func.py
> +    fig.show()
need to make `show()` optional, so it won't crash when there is no display

2019-06-18 10:59 UTC, esheldon commented on healsparse/visu_func.py
> +    fig.show()
Also, I've got cartopy/pyproj installed but nothing shows on the screen, and nothing gets saved to a file

2019-06-18 11:04 UTC, esheldon commented
Does it make sense to have an option to make the code zoom in on the area that is covered by the map?  For example, I'm implementing small geometric primitives and I'd like to visualize them, but this will I think show the entire sky and a  small circle won't be visible.

2019-06-18 11:32 UTC, erykoff commented
I haven't had a chance to look at the code yet (sorry), but @esheldon makes a very good point: the most useful part of `healsparse` is having high resolution over small areas.

2019-06-18 17:01 UTC, fjaviersanchez commented
Thanks for the suggestion! The code, as it is right now, can ingest a range of coordinates (`extent`) to show. If there's no extent passed, it will show the full sky. I can change the default behavior to show only the part of the map that is actually covered. Would you say that I should do that change?

2019-06-18 17:56 UTC, esheldon commented
`extent` would be enough in some cases, but not for complex maps.  In many cases we won't know what the extent is.

2020-05-09 00:43 UTC, fjaviersanchez commented
This is going to go outside of this package.

2020-05-09 00:43 UTC, closed without merging