Change camelCase to underscores and rationalize APIs
LSSTDESC/healsparse pull request #41
Opened 2020-01-27 15:43 UTC by erykoff

This is a major overhaul that also includes flake8 checking.  The following public APIs have been changed:

**In HealSparseMap**

`read(cls, filename, nsideCoverage=None, pixels=None, header=False)` to
`read(cls, filename, nside_coverage=None, pixels=None, header=False)`

`makeEmpty(cls, nsideCoverage, nsideSparse, dtype, primary=None,
sentinel=None)` to `make_empty(cls, nside_coverage, nside_sparse, dtype,
primary=None, sentinel=None)`

`convertHealpixMap(healpixMap, nsideCoverage, nest=True, sentinel=hp.UNSEEN)`
to `convert_healpix_map(healpix_map, nside_coverage, nest=True,
sentinel=hp.UNSEEN)`

`updateValues(self, pixel, values, nest=True)` to `update_values_pix(self,
pixels, values, nest=True)`

`getValueRaDec(self, ra, dec, validMask=False)` and `getValueThetaPhi(self,
theta, phi, validMask=False)` to `get_values_pos(self, theta_or_ra, phi_or_dec,
lonlat=False, valid_mask=False)`

`getValuePixel(self, pixel, nest=True, validMask=False)` to
`get_values_pix(self, pixels, nest=True, valid_mask=False)`

`coverageMap` to `coverage_map`

`coverageMask` to `coverage_mask`

`nsideCoverage` to `nside_coverage`

`nsideSparse` to `nside_sparse`

`isIntegerMap` to `is_integer_map`

`isRecArray` to `is_rec_array`

`generateHealpixMap(self, nside=None, reduction='mean', key=None)` to
`generate_healpix_map(self, nside=None, reduction='mean', key=None)`

`validPixels` to `valid_pixels`

`applyMask(self, maskMap, maskBits=None, inPlace=True)` to `apply_mask(self,
mask_map, mask_bits=None, in_place=True)`

`getSingle(self, key, sentinel=None)` to `get_single(self, key, sentinel=None)`

**In HealSparseRandoms**

`makeUniformRandomsFast(sparseMap, nRandom, nsideRandoms=2**23, rng=None)` to
`make_uniform_randoms_fast(sparse_map, n_random, nside_randoms=2**23,
rng=None)`

`makeUniformRandoms(sparseMap, nRandom, rng=None)` to
`make_uniform_randoms(sparse_map, n_random, rng=None)`

**In Operations**

`sumUnion(mapList)` to `sum_union(map_list)`

`sumIntersection(mapList)` to `sum_intersection(map_list)`

`productUnion(mapList)` to `product_union(map_list)`

`productIntersection(mapList)` to `product_intersection(map_list)`

`orUnion(mapList)` to `or_union(map_list)`

`orIntersection(mapList)` to `or_intersection(map_list)`

`andUnion(mapList)` to `and_union(map_list)`

`andIntersection(mapList)` to `and_intersection(map_list)`

`xorUnion(mapList)` to `xor_union(map_list)`

`xorIntersection(mapList)` to `xor_intersection(map_list)`

2020-01-27 20:35 UTC, fjaviersanchez requested changes
Thanks a lot @erykoff. This is great! I ran the tests and they work on my laptop and everything seems to work (so that's great news!). There are a couple of places with camelcase text but it's mostly unexposed to the user, but since there are only a few of these things left, I'd suggest to change them to underscore.

2020-01-27 20:35 UTC, fjaviersanchez commented on healsparse/healSparseRandoms.py
> +    bitShift = 2 * int(np.round(np.log(nside_randoms / sparse_map.nside_sparse) / np.log(2)))
`bitShift` is not visible to the user so I guess it's fine it's camelcase.

2020-01-27 20:35 UTC, fjaviersanchez commented on healsparse/healSparseRandoms.py
> +    raRand, dec_rand = hp.pix2ang(nside_randoms,
`ra_rand` instead of `raRand`? But again, this is not visible to the user.

2020-01-27 20:35 UTC, fjaviersanchez commented on healsparse/healSparseRandoms.py
>      maxGen = 1000000
`max_gen`?

2020-01-27 20:35 UTC, fjaviersanchez commented on tests/test_updateValues.py
>      def test_updateValues_inorder(self):
change to `test_update_values_inorder`?

2020-01-27 20:35 UTC, fjaviersanchez commented on tests/test_updateValues.py
>      def test_updateValues_outoforder(self):
change to `test_update_values_outoforder`?

2020-01-30 21:06 UTC, fjaviersanchez approved these changes
Looks good to me! Thanks @erykoff

2020-01-31 01:40 UTC, esheldon commented
I haven't gone through every change, but I think it makes sense to use pythonic names.

Tools like flake8 will enforce it in most places I think, so you would have to configure flake8 especially to ignore such things.

2020-02-04 19:08 UTC, merged